plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'io.github.Guimaraes131'
version = '0.0.1-SNAPSHOT'
description = 'A Spring Boot MVC project to manage motorcycle parking lots, enabling vehicle registration, space tracking, and reservation management.'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// --- Dependências da aplicação ---
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-database-postgresql'
	implementation 'io.hypersistence:hypersistence-utils-hibernate-63:3.11.0'
	implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'

	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'

	// --- Dependências para testes ---
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Selenium WebDriver
	testImplementation 'org.seleniumhq.selenium:selenium-java:4.21.0'

	// JUnit 5
	testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'

	// WebDriverManager (para baixar e gerenciar o ChromeDriver automaticamente)
	testImplementation 'io.github.bonigarcia:webdrivermanager:5.8.0'
}

tasks.named('test') {
	useJUnitPlatform()
}
